---

- hosts: all
  
  become: true

  vars:
    # Variable holding the login credentials
    my_jenkins_params:
      url_username: admin
      url_password: "{{jenkins_pass.stdout}}"
      url: http://192.168.56.195:8080

  tasks:


  - name: get jenkins initial admin password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkins_pass
    become_user: root

  - name: install plugins
    jenkins_plugin:
      name: github
      # This is where we use the above variable
      params: "{{ my_jenkins_params }}"
      state: present

  - name: restart jenkins if required
    service:
      name: jenkins
      state: restarted