---

- hosts: tomcat

  become: true

  tasks:


  - name: Delete existing Nginx config file
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent

  - name: Create a new config file
    blockinfile:
      path: /etc/nginx/conf.d/default.conf
      create: yes
      mode: "u=rw,g=r,o=r"
      block: |
        upstream tomcat {
                        server 192.168.56.197:8080;
                        }

        server {
                listen 80;
                server_name tomcat;

                location / {
                            proxy_pass http://tomcat/hello_world-0.0.1-SNAPSHOT/;
                            proxy_set_header Host $host;
                            proxy_set_header X-Real-IP $remote_addr;
                            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                            proxy_set_header X-Forwarded-Proto $scheme;
                            proxy_set_header Connection "";
                            proxy_http_version 1.1;
                            }
                }

  - name: Restart Nginx
    service: 
      name: nginx
      state: restarted
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success