---

- hosts: all
  
  become: true

  tasks:

  - name: get jenkins initial admin password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: password_var
    become_user: root

  - name: set jenkins admin password fact
    set_fact:
      jenkins_password: '{{ password_var.stdout }}'

  - debug:
      msg: '{{ password_var.stdout }}'

  - name: install plugin
    jenkins_plugin:
      name: git
      params:
        url: http://192.168.56.195:8080 
        url_username: admin
        url_password: '{{ jenkins_password }}'
      state: present

  - name: install plugin
    jenkins_plugin:
      name: deploy
      params:
        url: http://192.168.56.195:8080 
        url_username: admin
        url_password: '{{ jenkins_password }}'
      state: present





  - name: restart jenkins if required
    service:
      name: jenkins
      state: restarted

  - name: wait
    wait_for:
      timeout: 10

  