---

- hosts: tomcat

  become: true

  environment:
    JAVA_HOME: /usr/lib/jvm/default-java

  tasks:

  - name: Grab Tomcat archive with pre-configured parameters from GitHub
    git:
      repo: https://github.com/edrevpac/tomcat.git
      dest: /opt/tomcat
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success

  - pause:

  - name: Start the Tomcat engine
    command: "nohup /opt/tomcat/bin/startup.sh start"
    register: command_result
    retries: 3
    delay: 3
    become_user: root