---

- hosts: jenkins

  become: true

  environment:
    JAVA_HOME: /usr/lib/jvm/default-java

  tasks:

  - name: Import Jenkins APT key
    apt_key: 
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success
      
  - name: Add Jenkins package APT repository
    apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success
      
  - name: Install Jenkins LTS
    apt:
      name: jenkins
      update_cache: yes
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success

  - name: Start Jenkins
    service:
      name: jenkins
      state: started
      enabled: yes
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success

  - name: Wait 60 seconds for good measure
    wait_for:
      timeout: 60
