---

- hosts: all

  tasks:

  - name: install JDK
    apt:
      name: default-jdk-headless
      state: present
    become: true

  - name: set JAVA_HOME environment variables
    lineinfile:
      path: ~/.profile
      line: 'JAVA_HOME=/usr/lib/jvm/default-java'
      insertbefore: BOF
    become_user: vagrant

  - name: set JRE_HOME environment variables
    lineinfile:
      path: ~/.profile
      line: 'JRE_HOME=/usr/lib/jvm/default-java/jre'
      insertbefore: BOF
    become_user: vagrant
