---

- hosts: all
  
  tasks:

  - name: download maven
    get_url:
      url: http://www-eu.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
      dest: /
    become: true

  - name: install unzip
    apt:
      name: unzip
      state: present
    become: true

  - name: download and extract Maven archive
    unarchive: 
      src: /apache-maven-3.5.0-bin.zip
      dest: /opt
      remote_src: yes
    become: true

  - name: create symlink
    file:
      src: /opt/apache-maven-3.5.0
      dest: /maven
      owner: vagrant
      state: link
    become: true

  - name: set environment variables
    lineinfile:
      path: ~/.profile
      line: 'M2_HOME=/opt/apache-maven-3.5.0'
      insertbefore: BOF

  - name: set environment variables
    lineinfile:
      path: ~/.profile
      line: 'M2=/opt/apache-maven-3.5.0/bin'
      insertbefore: BOF

  - name: set environment variables
    lineinfile:
      path: ~/.profile
      line: 'PATH=/opt/apache-maven-3.5.0/bin:$PATH'
      insertbefore: BOF