---

- hosts: all

  become: true

  tasks:

  - name: Install APT HTTPS transport capability
    apt: 
      name: apt-transport-https
      state: present
      update_cache: yes
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success