---

- hosts: all

  become: true  

  tasks:

  - name: install tomcat & prerequisites
    apt:
      name:
        - default-jdk-headless
        - tomcat8
        - tomcat8-docs
        - tomcat8-admin
        - tomcat8-examples
      update_cache: yes

  - name: set jdk environment variables
    lineinfile:
      path: ~/.profile
      line: 'JAVA_HOME=/usr/lib/jvm/default-java'
      insertbefore: BOF

  - name: set jre environment variables
    lineinfile:
      path: ~/.profile
      line: 'JRE_HOME=/usr/lib/jvm/default-java/jre'
      insertbefore: BOF

  - name: set tomcat environment variables
    lineinfile:
      path: ~/.profile
      line: 'CATALINA_HOME=/var/lib/tomcat8'
      insertbefore: BOF
    become_user: vagrant

  - name: remove pre-made tomcat-users file so we can set up our own
    file:
      path: /var/lib/tomcat8/conf/tomcat-users.xml
      state: absent

  - name: create new tomcat-users file
    file:
      path: /var/lib/tomcat8/conf/tomcat-users.xml
      state: touch
      mode: "u=rw,g=r,o=r"

  - name: create new tomcat user 
    blockinfile:
      path: /var/lib/tomcat8/conf/tomcat-users.xml
      block: |
        <?xml version="1.0" encoding="UTF-8?>
        <tomcat-users>
        <pre><role rolename="manager-gui"/>
          <role rolename="manager-script"/>
          <role rolename="manager-jmx"/>
          <role rolename="manager-status"/>
          <role rolename="admin-gui"/>
          <role rolename="admin-script"/>
          <user username="cap" password="123" roles="manager-gui,manager-<wbr />script,manager-jmx,manager-<wbr />status,admin-gui,admin-script"<wbr />/>
        </tomcat-users>

  - name: enable tomcat8 service to run on boot
    service:
      name: tomcat8
      enabled: yes
      state: started
