---

- hosts: all

  become: true

  tasks:

  - name: Install Java 8 JDK
    apt: 
      name: default-jdk-headless
      state: present
      update_cache: yes
    register: command_result
    retries: 3
    delay: 3
    until: command_result | success

  - pause: