---

- hosts: all

  become: true  

  tasks:

  - name: install JDK
    apt:
      update_cache: yes
      name: default-jdk-headless
      state: present
    become: true

  - name: set JAVA_HOME environment variables
    lineinfile:
      path: ~/.profile
      line: 'JAVA_HOME=/usr/lib/jvm/default-java'
      insertbefore: BOF

  - name: set JRE_HOME environment variables
    lineinfile:
      path: ~/.profile
      line: 'JRE_HOME=/usr/lib/jvm/default-java/jre'
      insertbefore: BOF

  - name: install tomcat8
    apt:
      package: tomcat8
      state: present

  - name: remove pre-made user config so we can set up our own
    file:
      path: /etc/tomcat8/tomcat-users.xml
      state: absent

  - name: create new tomcat-users file
    file:
      path: /etc/tomcat8/tomcat-users.xml
      state: touch
      mode: "u=rw,g=r,o=r"

  - name: set environment variables
    lineinfile:
      path: ~/.profile
      line: 'CATALINA_HOME=/usr/share/tomcat8/'
      insertbefore: BOF
    become_user: vagrant

  - name: create logs folder
    file:
      path: /usr/share/tomcat8/logs
      state: directory
      mode: 0644

  - name: set tomcat-users
    blockinfile:
      path: /etc/tomcat8/tomcat-users.xml
      block: |
        <?xml version="1.0" encoding="UTF-8?>
        <tomcat-users>
        <pre><role rolename="manager-gui"/>
          <role rolename="manager-script"/>
          <role rolename="manager-jmx"/>
          <role rolename="manager-status"/>
          <role rolename="admin-gui"/>
          <role rolename="admin-script"/>
          <user username="cap" password="123" roles="manager-gui,manager-<wbr />script,manager-jmx,manager-<wbr />status,admin-gui,admin-script"<wbr />/>
        </tomcat-users>

  - name: launch tomcat service
    shell: /usr/share/tomcat8/bin/startup.sh