---

- hosts: all

  become: true

  environment:
    JAVA_HOME: /usr/lib/jvm/default-java

  tasks:

  - name: install misc stuff
    apt: 
      name: 
        - git
        - default-jdk-headless
      state: present
      update_cache: yes

  - name: get tomcat from where it's hiding
    git:
      repo: https://github.com/edrevpac/tomcat.git
      dest: /opt/tomcat

  - name: wait a while and listen
    wait_for:
      timeout: 10

  - name: fire that bad boy up
    shell: /opt/tomcat/bin/startup.sh
    become_user: root
  