---

- hosts: all

  become: true

  tasks:

  - name: get jenkins initial admin password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: password_var
    become_user: root

  - name: set jenkins admin password fact
    set_fact:
      jenkins_password: '{{ password_var.stdout }}'

  - debug:
      msg: '{{ password_var.stdout }}'

  - name: install plugin
    jenkins_plugin:
      name: git
      params:
        url: http://192.168.56.196:8080
        url_username: admin
        url_password: '{{ jenkins_password }}'
      state: present

  - name: install plugin
    jenkins_plugin:
      name: deploy
      params:
        url: http://192.168.56.196:8080
        url_username: admin
        url_password: '{{ jenkins_password }}'
      state: present


  - name: grab the pre-configured files from wonderland
    get_url: 
      url: https://raw.githubusercontent.com/edrevpac/jenkins/master/{{item}}
      dest: /var/lib/jenkins
      owner: jenkins
      group: jenkins
#      mode: 0755
    with_items:
      - config.xml
      - credentials.xml
      - hudson.tasks.Maven.xml
      - jenkins.model.JenkinsLocationConfiguration.xml
      - jenkins.mvn.GlobalMavenConfig.xml
      - org.jenkinsci.plugins.gitclient.JGitApacheTool.xml
      - org.jenkinsci.plugins.gitclient.JGitTool.xml
      - hudson.model.Job.serverCookie
      - hudson.plugins.git.GitSCM.xml
      - hudson.tasks.Mailer.xml
      - hudson.tasks.Shell.xml
      - hudson.triggers.SCMTrigger.xml
      - jenkins.model.ArtifactManagerConfiguration.xml


  - name: create the jobs folder
    file:
      path: /var/lib/jenkins/jobs/hello_world
      state: directory
      owner: jenkins
      group: jenkins
#      mode: 0755

  - name: grab the pre-configured files from wonderland
    get_url: 
      url: https://raw.githubusercontent.com/edrevpac/jenkins/master/hello_world/config.xml
      dest: /var/lib/jenkins/jobs/hello_world
      owner: jenkins
      group: jenkins
#      mode: 0755

  - name: restart jenkins if required
    service:
      name: jenkins
      state: restarted